/* Правки навигации, плеера, Топ-100, подвала и юридических страниц. */
(function(){
'use strict';
function $(id){return document.getElementById(id)}
function css(){if($('request-fixes-css'))return;var s=document.createElement('style');s.id='request-fixes-css';s.textContent='.nav [data-tab="kodik"]{display:none!important}.fs-btn{display:none!important}.player.playing.hide-ui .p-controls{opacity:0!important;pointer-events:none!important}.player.playing.hide-ui .p-bigplay{opacity:0!important;pointer-events:none!important}.player:fullscreen,.player:-webkit-full-screen{width:100vw!important;height:100dvh!important;max-width:none!important;border:0!important;border-radius:0!important;background:#000}.player:fullscreen video,.player:-webkit-full-screen video{width:100%!important;height:100%!important;object-fit:contain!important}.player:fullscreen .p-controls,.player:-webkit-full-screen .p-controls{padding-right:max(12px,env(safe-area-inset-right));padding-bottom:max(10px,env(safe-area-inset-bottom));padding-left:max(12px,env(safe-area-inset-left))}.legal-page{padding-top:calc(var(--header-h) + 28px);max-width:820px}.legal-page h1{margin-bottom:18px}.legal-page h2{margin-top:28px}.legal-page p,.legal-page li{color:var(--muted);line-height:1.65}.legal-links{display:flex;flex-wrap:wrap;gap:10px 18px;margin-bottom:12px}.legal-links a{color:var(--text)}.legal-links a:hover{color:var(--accent)}.foot{padding-bottom:max(34px,calc(104px + env(safe-area-inset-bottom)))}@media(max-width:700px){.player .p-row{flex-wrap:nowrap!important;overflow:hidden}.player .p-volume input{width:52px!important}.player .p-time{font-size:11px!important;padding-inline:2px!important}.player .p-btn{min-width:36px!important;width:36px!important}.player #pSpeedBtn,.player #pQualityBtn{width:auto!important;padding-inline:6px!important}.player.playing.hide-ui{cursor:none}}';document.head.appendChild(s)}
function nav(){document.querySelectorAll('.nav [data-tab="kodik"]').forEach(function(n){n.remove()})}
function back(){var b=document.querySelector('#kbRoot .link-btn.back');if(!b)return;b.textContent='← Назад';b.setAttribute('aria-label','Вернуться в каталог');b.onclick=function(e){if(history.length>1){e.preventDefault();history.back()}}}
function topScores(){document.querySelectorAll('.top-score').forEach(function(n){var v=parseFloat(n.textContent);n.hidden=!isFinite(v);if(isFinite(v))n.textContent=v.toFixed(1)})}
function player(){document.querySelectorAll('.fs-btn').forEach(function(n){n.remove()});var root=$('playerRoot'),video=$('player');if(!root||!video||root.dataset.playFix)return;root.dataset.playFix='1';function sync(){root.classList.toggle('playing',!video.paused&&!video.ended)}video.addEventListener('play',sync);video.addEventListener('pause',sync);video.addEventListener('ended',sync);sync()}
var PAGES={terms:{title:'Пользовательское соглашение',body:'<p>AnimRu предоставляет интерфейс для поиска информации об аниме и доступа к материалам сторонних видеосервисов. Используя сайт, вы соглашаетесь соблюдать законодательство своей страны и правила источников контента.</p><h2>Условия использования</h2><ul><li>Сервис предоставляется без гарантии постоянной доступности сторонних источников.</li><li>Запрещены попытки нарушить работу сайта, базы данных и аккаунтов других пользователей.</li><li>Пользователь отвечает за сохранность своей учётной записи.</li></ul><h2>Изменения</h2><p>Условия могут обновляться вместе с функциональностью проекта.</p>'},privacy:{title:'Политика конфиденциальности',body:'<p>AnimRu хранит только данные, необходимые для аккаунта, списков, прогресса просмотра, оценок и комментариев.</p><h2>Что хранится</h2><ul><li>Почта и имя профиля.</li><li>Списки, оценки и прогресс просмотра.</li><li>Технические данные, необходимые для офлайн-режима.</li></ul><h2>Управление данными</h2><p>Сохранение можно экспортировать или удалить в профиле. Пароли обрабатываются Supabase и не сохраняются в открытом виде.</p>'},rights:{title:'Правообладателям',body:'<p>AnimRu не размещает видеофайлы на собственных серверах. Плееры и метаданные предоставляются AniLibria и Kodik.</p><p>Для обращения укажите произведение, ссылку на страницу, подтверждение прав и требуемое действие.</p><p>Контакт: <a href="mailto:nozirovruillo@gmail.com">nozirovruillo@gmail.com</a></p>'}};
function footer(){var wrap=document.querySelector('.foot .wrap');if(!wrap||wrap.dataset.legal)return;wrap.dataset.legal='1';wrap.innerHTML='<nav class="legal-links" aria-label="Документы"><a href="#/terms">Пользовательское соглашение</a><a href="#/privacy">Конфиденциальность</a><a href="#/rights">Правообладателям</a></nav><p>AnimRu использует метаданные AniLibria и Kodik. Видео воспроизводится со стороны источников.</p><p class="muted small">© '+new Date().getFullYear()+' AnimRu. Некоммерческий проект.</p>'}
function legal(){var key=(location.hash.match(/^#\/(terms|privacy|rights)/)||[])[1];var view=$('view-legal');if(!key){if(view)view.hidden=true;return}if(!view){view=document.createElement('section');view.id='view-legal';view.className='view wrap legal-page';$('app').appendChild(view)}document.querySelectorAll('#app>.view').forEach(function(n){n.hidden=n!==view});view.hidden=false;view.innerHTML='<a class="link-btn" href="#/">← Назад</a><h1>'+PAGES[key].title+'</h1>'+PAGES[key].body;document.title=PAGES[key].title+' - AnimRu';scrollTo(0,0)}
function persist(){document.addEventListener('click',function(e){if(!(e.target.closest&&e.target.closest('#dlBtn')))return;if(navigator.storage&&navigator.storage.persist)navigator.storage.persist().catch(function(){})},true)}
function pass(){css();nav();back();topScores();player();footer();legal()}
function start(){persist();pass();window.addEventListener('hashchange',function(){setTimeout(pass,60)});new MutationObserver(function(){clearTimeout(start.t);start.t=setTimeout(pass,100)}).observe(document.body,{childList:true,subtree:true,characterData:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
