/* Расписание выхода серий AniLibria. */
(function(){
'use strict';
var API=['https:','','anilibria.top','api','v1'].join('/'),DAYS=[[1,'Понедельник'],[2,'Вторник'],[3,'Среда'],[4,'Четверг'],[5,'Пятница'],[6,'Суббота'],[7,'Воскресенье']],loaded=false,loading=false;
function $(id){return document.getElementById(id)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function css(){if($('schedule-css'))return;var s=document.createElement('style');s.id='schedule-css';s.textContent='#view-schedule{padding-top:calc(var(--header-h) + 24px)}.sch-head{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:18px}.sch-head h1{margin:0}.sch-day{margin-bottom:26px}.sch-day-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.sch-day-name{font-weight:650}.sch-today{padding:3px 7px;border-radius:var(--r-sm);background:var(--accent);color:var(--accent-ink);font-size:11px}.sch-line{flex:1;height:1px;background:var(--line)}.sch-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));gap:12px}.sch-card{display:grid;gap:7px;color:inherit}.sch-thumb{position:relative;aspect-ratio:2/3;border:1px solid var(--line);border-radius:var(--r);overflow:hidden;background:var(--surface-2)}.sch-thumb img{width:100%;height:100%;object-fit:cover}.sch-ep{position:absolute;left:7px;bottom:7px;padding:3px 7px;border-radius:var(--r-sm);background:#0a0a0bcc;color:#fff;font-size:11px}.sch-name{font-size:13px;line-height:1.3}.sch-sub,.sch-empty{font-size:12px;color:var(--muted)}@media(max-width:520px){.sch-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}}';document.head.appendChild(s)}
function nav(){var n=$('nav');if(!n||n.querySelector('[data-tab="schedule"]'))return;var a=document.createElement('a');a.href='#/schedule';a.className='nav-link';a.dataset.tab='schedule';a.textContent='Расписание';n.appendChild(a)}
function view(){var v=$('view-schedule');if(v)return v;v=document.createElement('section');v.id='view-schedule';v.className='view wrap';v.hidden=true;v.innerHTML='<div class="sch-head"><h1>Расписание AniLibria</h1><span id="schStatus" class="muted small"></span></div><div id="schBody"></div>';$('app').appendChild(v);return v}
function list(j){if(Array.isArray(j))return j;if(j&&Array.isArray(j.data))return j.data;var out=[];if(j&&typeof j==='object')Object.keys(j).forEach(function(k){if(Array.isArray(j[k]))j[k].forEach(function(x){out.push({day:k,release:x.release||x,episode:x.new_episode||x.episode})})});return out}
function load(){if(loaded||loading)return;loading=true;$('schStatus').textContent='Загружаем…';fetch(API+'/anime/schedule/week',{headers:{Accept:'application/json'}}).then(function(r){if(!r.ok)throw Error();return r.json()}).then(list).then(render).catch(function(){$('schStatus').textContent='';$('schBody').innerHTML='<p class="sch-empty">Не удалось загрузить расписание. Попробуйте обновить страницу.</p>'}).then(function(){loading=false})}
function day(x,r){var v=x.publish_day||x.day||r.publish_day;if(v&&typeof v==='object')v=v.value;v=parseInt(v,10);return v>=1&&v<=7?v:0}function poster(r){var p=r.poster||{},u=(p.optimized&&p.optimized.src)||p.src||'';return !u?'':/^https?:/.test(u)?u:API.replace('/api/v1','')+u}
function card(x){var r=x.release||x,e=x.episode||x.new_episode,n=e&&(e.ordinal||e.sort_order||e),bits=[r.year,r.type&&r.type.description].filter(Boolean).join(' · ');return'<a class="sch-card" href="#/title/'+encodeURIComponent(r.id)+'"><span class="sch-thumb">'+(poster(r)?'<img loading="lazy" src="'+esc(poster(r))+'" alt="">':'')+(n?'<span class="sch-ep">'+esc(n)+' серия</span>':'')+'</span><span class="sch-name">'+esc(r.name&&(r.name.main||r.name.english)||'Без названия')+'</span><span class="sch-sub">'+esc(bits)+'</span></a>'}
function render(items){var groups={1:[],2:[],3:[],4:[],5:[],6:[],7:[]};items.forEach(function(x){var r=x.release||x,k=day(x,r);if(r&&r.id&&groups[k])groups[k].push(x)});var today=new Date().getDay()||7,html='';DAYS.forEach(function(d){var a=groups[d[0]];html+='<section class="sch-day"><div class="sch-day-head"><span class="sch-day-name">'+d[1]+'</span>'+(d[0]===today?'<span class="sch-today">сегодня</span>':'')+'<span class="sch-line"></span><span class="muted small">'+a.length+'</span></div>'+(a.length?'<div class="sch-grid">'+a.map(card).join('')+'</div>':'<p class="sch-empty">Выход серий не заявлен.</p>')+'</section>'});$('schBody').innerHTML=html;$('schStatus').textContent=items.length+' тайтлов';loaded=true}
function apply(){var on=/^#\/schedule/.test(location.hash||''),v=view();if(!on){v.hidden=true;return}document.querySelectorAll('#app>.view').forEach(function(n){n.hidden=n!==v});v.hidden=false;document.querySelectorAll('.nav-link').forEach(function(a){a.classList.toggle('active',a.dataset.tab==='schedule')});document.title='Расписание AniLibria — AnimRu';load();scrollTo(0,0)}
function start(){css();nav();view();apply();window.addEventListener('hashchange',function(){setTimeout(apply,0)})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
